// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5HLhrjgPH2UfhHEUDcch-DJeXal8JXyU',
    appId: '1:436396043605:web:ec61f8a9c2504f85ff93dc',
    messagingSenderId: '436396043605',
    projectId: 'hotelbookingtz',
    authDomain: 'hotelbookingtz.firebaseapp.com',
    storageBucket: 'hotelbookingtz.firebasestorage.app',
    measurementId: 'G-KPTFBP2NVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBViFXnpqQ8RKqM7tkHuZOZQBB4NIpdY1w',
    appId: '1:436396043605:android:a37ace93fd2eff2fff93dc',
    messagingSenderId: '436396043605',
    projectId: 'hotelbookingtz',
    storageBucket: 'hotelbookingtz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRCknFPmzR5gAMi5KSO8iyHSkX6ytuYpQ',
    appId: '1:436396043605:ios:f4d195dfb937c5c1ff93dc',
    messagingSenderId: '436396043605',
    projectId: 'hotelbookingtz',
    storageBucket: 'hotelbookingtz.firebasestorage.app',
    iosBundleId: 'com.example.hotelbookingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRCknFPmzR5gAMi5KSO8iyHSkX6ytuYpQ',
    appId: '1:436396043605:ios:f4d195dfb937c5c1ff93dc',
    messagingSenderId: '436396043605',
    projectId: 'hotelbookingtz',
    storageBucket: 'hotelbookingtz.firebasestorage.app',
    iosBundleId: 'com.example.hotelbookingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5HLhrjgPH2UfhHEUDcch-DJeXal8JXyU',
    appId: '1:436396043605:web:8a224a639a42a46bff93dc',
    messagingSenderId: '436396043605',
    projectId: 'hotelbookingtz',
    authDomain: 'hotelbookingtz.firebaseapp.com',
    storageBucket: 'hotelbookingtz.firebasestorage.app',
    measurementId: 'G-VGGBPKMT5Y',
  );

}